#!/bin/bash
# Quick test to verify profiling works

echo "=== Testing Profiling Integration ==="
echo ""
echo "✅ Build successful"
echo "✅ --profile flag added to CLI"
echo ""
echo "📋 Next: Run baseline performance test"
echo ""
echo "To test profiling (requires VPN server):"
echo ""
echo "  sudo ./zig-out/bin/vpnclient \\"
echo "      --server YOUR_SERVER \\"
echo "      --hub YOUR_HUB \\"
echo "      --user YOUR_USER \\"
echo "      --password YOUR_PASS \\"
echo "      --profile"
echo ""
echo "You should see output like:"
echo "  🔬 Performance profiling enabled"
echo "  [5.0s] RX: 10.2 Mbps (850 packets)"
echo "  [10.0s] RX: 10.5 Mbps (1700 packets)"
echo ""
echo "Press Ctrl+C to stop and see final metrics report."
echo ""
echo "📊 Expected baseline: ~10 Mbps"
echo ""
